### ISSUE TITLE
Registro - Validar campos de texto

### ISSUE THREAD

**Issue by gordojm** [enuelx/marketplace-profesores-particulares#6]
## Resumen

Realizar la validación de los campos en la página de registro.

- **Nombre:** no debe estar vacío
- **Apellido:** no debe estar vacío
- **Correo electrónico:** no debe estar vacío y debe ser una dirección válida (buscar validación con expresión regular)
- **Número de teléfono:** debe ser un número válido (solo acepta caracteres numéricos y un "+" al principio; buscar validación con expresión regular) 
- **Contraseña:** no debe estar vacío y debe ser una contraseña segura (debe tener entre 8 y 16 caracteres y contener al menos una minúscula, una mayúscula, un número y un carácter especial; buscar validación con expresión regular)

Si no se cumplen los requisitos, el campo debe resaltarse en rojo y mostrar un mensaje de error genérico para cada campo.

![Image](https://user-images.githubusercontent.com/37698974/192108399-217970aa-e444-4075-b347-783e611a8ee4.png)

**Comment by 3nu3l** [comment]
![Image](https://user-images.githubusercontent.com/14189815/192315726-72d5bd46-b6a1-4916-9165-5f9ed18a516c.png)


![Image](https://user-images.githubusercontent.com/14189815/192315648-4e7c3a0e-0b60-4010-8acc-eb00ad9a6afa.png)

**Comment by 3nu3l** [comment]
![Image](https://user-images.githubusercontent.com/14189815/192399973-b914cb1e-5659-47b3-94d9-992ae96259fc.png)

**Comment by 3nu3l** [comment]
cambio de regex de telefono, solo acepta + y numeros


![Image](https://user-images.githubusercontent.com/14189815/192400293-6965d786-8868-4383-9bb1-8c7e207e50fc.png)

**Comment by 3nu3l** [comment]
ejemplo de todo ok


![Image](https://user-images.githubusercontent.com/14189815/192400386-a8aab6b8-b56e-4d22-bab5-114f7a9c12e7.png)

**Comment by 3nu3l** [comment]
![Image](https://user-images.githubusercontent.com/14189815/192400400-e94a9a29-5e31-4fdf-8563-0dc229fea954.png)
